"""add_onboarding_complete_to_users

Revision ID: 1f88923e9ad0
Revises: b3c4d5e6f7g8
Create Date: 2026-02-26 11:48:06.230803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f88923e9ad0'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with default True (existing users have completed onboarding)
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), server_default='true', nullable=False))
    # After adding, remove the server_default so new users get False from Python model default
    op.alter_column('users', 'onboarding_complete', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_complete')
    # ### end Alembic commands ###
